// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nomination_api.DataBaseContext;

#nullable disable

namespace nomination_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("nomination_api.models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("nomination_api.models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventAction")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("nomination_api.models.Nomination", b =>
                {
                    b.Property<Guid>("NominationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Formal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NominatedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NominationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NominationLastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("NominationMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NominatorId")
                        .HasColumnType("TEXT");

                    b.HasKey("NominationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NominatedId");

                    b.HasIndex("NominatorId");

                    b.ToTable("Nominations");
                });

            modelBuilder.Entity("nomination_api.models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("nomination_api.models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UserLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nomination_api.models.Event", b =>
                {
                    b.HasOne("nomination_api.models.User", "User")
                        .WithMany("EventsGenerated")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nomination_api.models.Nomination", b =>
                {
                    b.HasOne("nomination_api.models.Category", "Category")
                        .WithMany("NominationsInCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nomination_api.models.User", "Nominated")
                        .WithMany("NominationsReceived")
                        .HasForeignKey("NominatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nomination_api.models.User", "Nominator")
                        .WithMany("NominationsGiven")
                        .HasForeignKey("NominatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Nominated");

                    b.Navigation("Nominator");
                });

            modelBuilder.Entity("nomination_api.models.User", b =>
                {
                    b.HasOne("nomination_api.models.Role", "Role")
                        .WithMany("UsersInRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("nomination_api.models.Category", b =>
                {
                    b.Navigation("NominationsInCategory");
                });

            modelBuilder.Entity("nomination_api.models.Role", b =>
                {
                    b.Navigation("UsersInRole");
                });

            modelBuilder.Entity("nomination_api.models.User", b =>
                {
                    b.Navigation("EventsGenerated");

                    b.Navigation("NominationsGiven");

                    b.Navigation("NominationsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
